/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Molinera
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        botonResHab = new javax.swing.JButton();
        botonResSal = new javax.swing.JButton();
        botonAltEmp = new javax.swing.JButton();
        botonVerResH = new javax.swing.JButton();
        botonVerResS = new javax.swing.JButton();
        botonVerE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 765));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hotel1.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hotel1.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));

        botonResHab.setBackground(new java.awt.Color(0, 153, 51));
        botonResHab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResHab.setForeground(new java.awt.Color(255, 255, 255));
        botonResHab.setText("<html><center style='display:block; width:100%; padding:();'>Reserva <br> de habitaciones</center></html>");
        botonResHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResHabActionPerformed(evt);
            }
        });

        botonResSal.setBackground(new java.awt.Color(0, 153, 51));
        botonResSal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResSal.setForeground(new java.awt.Color(255, 255, 255));
        botonResSal.setText("<html><center style='display:block; width:100%; padding:();'>Reserva <br> de Salones</center></html>");
        botonResSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResSalActionPerformed(evt);
            }
        });

        botonAltEmp.setBackground(new java.awt.Color(0, 153, 51));
        botonAltEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonAltEmp.setForeground(new java.awt.Color(255, 255, 255));
        botonAltEmp.setText("<html><center style='display:block; width:100%; padding:();'>Alta <br> de empleados</center></html>");
        botonAltEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltEmpActionPerformed(evt);
            }
        });

        botonVerResH.setBackground(new java.awt.Color(0, 153, 51));
        botonVerResH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonVerResH.setForeground(new java.awt.Color(255, 255, 255));
        botonVerResH.setText("<html><center style='display:block; width:100%; padding:();'>Ver Reservas <br> de Habitaciones</center></html>");
        botonVerResH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerResHActionPerformed(evt);
            }
        });

        botonVerResS.setBackground(new java.awt.Color(0, 153, 51));
        botonVerResS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonVerResS.setForeground(new java.awt.Color(255, 255, 255));
        botonVerResS.setText("<html><center style='display:block; width:100%; padding:();'>Ver Reserva <br> de Salones</center></html>");
        botonVerResS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerResSActionPerformed(evt);
            }
        });

        botonVerE.setBackground(new java.awt.Color(0, 153, 51));
        botonVerE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonVerE.setForeground(new java.awt.Color(255, 255, 255));
        botonVerE.setText("<html><center style='display:block; width:100%; padding:();'>Ver <br> Empleados</center></html>");
        botonVerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(botonResHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(botonResSal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(botonAltEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(botonVerResH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(botonVerResS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(botonVerE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonResHab, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResSal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAltEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerResH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerResS, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerE, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonResHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResHabActionPerformed
        ReservaHabitaciones rh = new ReservaHabitaciones(this, rootPaneCheckingEnabled);
        rh.setVisible(true);
    }//GEN-LAST:event_botonResHabActionPerformed

    private void botonResSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResSalActionPerformed
        ReservaSalones rs = new ReservaSalones(this, rootPaneCheckingEnabled);
        rs.setVisible(true);
    }//GEN-LAST:event_botonResSalActionPerformed

    private void botonAltEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltEmpActionPerformed
        AltaEmpleados ae = new AltaEmpleados(this, rootPaneCheckingEnabled);
        ae.setVisible(true);
    }//GEN-LAST:event_botonAltEmpActionPerformed

    private void botonVerResHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerResHActionPerformed
        ListadoReservaHabitaciones lrh= new ListadoReservaHabitaciones(this, rootPaneCheckingEnabled);
        lrh.setVisible(true);
    }//GEN-LAST:event_botonVerResHActionPerformed

    private void botonVerResSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerResSActionPerformed
        ListadoReservaSalones lrs= new ListadoReservaSalones(this, rootPaneCheckingEnabled);
        lrs.setVisible(true);
    }//GEN-LAST:event_botonVerResSActionPerformed

    private void botonVerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerEActionPerformed
        ListadoEmpleados le= new ListadoEmpleados(this, rootPaneCheckingEnabled);
        le.setVisible(true);
    }//GEN-LAST:event_botonVerEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAltEmp;
    private javax.swing.JButton botonResHab;
    private javax.swing.JButton botonResSal;
    private javax.swing.JButton botonVerE;
    private javax.swing.JButton botonVerResH;
    private javax.swing.JButton botonVerResS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
