/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import bbdd.ConsultasClientes;
import bbdd.ConsultasEmpleados;
import bbdd.ConsultasSalones;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Salones;

/**
 *
 * @author Molinera
 */
public class ReservaSalones extends javax.swing.JDialog {

    private Object s;

    /**
     * Creates new form ReservaSalones
     */
    public ReservaSalones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelDatosCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonRegistrarCliente = new javax.swing.JButton();
        campoDni = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoDireccion = new javax.swing.JTextField();
        campoCp = new javax.swing.JTextField();
        campoLocalidad = new javax.swing.JTextField();
        botonComDni = new javax.swing.JButton();
        panelReserva = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        campoNrPers = new javax.swing.JTextField();
        comboCatering = new javax.swing.JComboBox<>();
        botonReserva = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 598));

        panelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        panelDatosCliente.setAlignmentX(0.2F);
        panelDatosCliente.setAlignmentY(0.2F);

        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("DNI");

        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Nombre");

        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Apellidos");

        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Telefono");

        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Email");

        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Direccion");

        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("CP");

        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Localidad");

        botonRegistrarCliente.setBackground(new java.awt.Color(204, 204, 204));
        botonRegistrarCliente.setForeground(new java.awt.Color(153, 153, 153));
        botonRegistrarCliente.setText("Registrar Cliente");
        botonRegistrarCliente.setEnabled(false);
        botonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarClienteActionPerformed(evt);
            }
        });

        campoDni.setBackground(new java.awt.Color(204, 204, 204));
        campoDni.setAlignmentX(0.2F);
        campoDni.setAlignmentY(0.2F);

        campoNombre.setAlignmentX(0.2F);
        campoNombre.setAlignmentY(0.2F);
        campoNombre.setEnabled(false);

        campoApellidos.setAlignmentX(0.2F);
        campoApellidos.setAlignmentY(0.2F);
        campoApellidos.setEnabled(false);

        campoTelefono.setAlignmentX(0.2F);
        campoTelefono.setAlignmentY(0.2F);
        campoTelefono.setEnabled(false);

        campoEmail.setAlignmentX(0.2F);
        campoEmail.setAlignmentY(0.2F);
        campoEmail.setEnabled(false);

        campoDireccion.setAlignmentX(0.2F);
        campoDireccion.setAlignmentY(0.2F);
        campoDireccion.setEnabled(false);

        campoCp.setAlignmentX(0.2F);
        campoCp.setAlignmentY(0.2F);
        campoCp.setEnabled(false);

        campoLocalidad.setAlignmentX(0.2F);
        campoLocalidad.setAlignmentY(0.2F);
        campoLocalidad.setEnabled(false);

        botonComDni.setBackground(new java.awt.Color(0, 0, 0));
        botonComDni.setForeground(new java.awt.Color(255, 153, 0));
        botonComDni.setText("Comprobar DNI");
        botonComDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosClienteLayout = new javax.swing.GroupLayout(panelDatosCliente);
        panelDatosCliente.setLayout(panelDatosClienteLayout);
        panelDatosClienteLayout.setHorizontalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonComDni, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDireccion)
                                    .addComponent(campoCp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelDatosClienteLayout.setVerticalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonComDni))
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(campoCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(botonRegistrarCliente)
                .addContainerGap())
        );

        panelReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE LA RESERVA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Fecha ");

        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("Nº  de personas");

        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("Catering");

        fecha.setBackground(new java.awt.Color(204, 204, 204));
        fecha.setAlignmentX(0.2F);
        fecha.setAlignmentY(0.2F);

        campoNrPers.setAlignmentX(0.2F);
        campoNrPers.setAlignmentY(0.2F);
        campoNrPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNrPersActionPerformed(evt);
            }
        });

        comboCatering.setBackground(new java.awt.Color(204, 204, 204));
        comboCatering.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "almuerzo", "comida", "desayuno", "cena" }));

        javax.swing.GroupLayout panelReservaLayout = new javax.swing.GroupLayout(panelReserva);
        panelReserva.setLayout(panelReservaLayout);
        panelReservaLayout.setHorizontalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelReservaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(campoNrPers)
                    .addComponent(comboCatering, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        panelReservaLayout.setVerticalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(9, 9, 9)
                        .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(campoNrPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15))
                    .addGroup(panelReservaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCatering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        botonReserva.setBackground(new java.awt.Color(255, 153, 0));
        botonReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonReserva.setForeground(new java.awt.Color(153, 153, 153));
        botonReserva.setText("Reserva");
        botonReserva.setEnabled(false);
        botonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservaActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Detalles de la Reserva");

        botonFactura.setText("Generar Factura");
        botonFactura.setEnabled(false);
        botonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturaActionPerformed(evt);
            }
        });

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(botonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reserva de Salones");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarClienteActionPerformed
        botonRegistrarCliente();
    }//GEN-LAST:event_botonRegistrarClienteActionPerformed

    private void botonComDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComDniActionPerformed
        botonComDni();
    }//GEN-LAST:event_botonComDniActionPerformed

    private void campoNrPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNrPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNrPersActionPerformed

    private void botonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservaActionPerformed
        botonReserva();
    }//GEN-LAST:event_botonReservaActionPerformed

    private void botonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturaActionPerformed
        botonFactura();
    }//GEN-LAST:event_botonFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaSalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaSalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaSalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaSalones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReservaSalones dialog = new ReservaSalones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botonComDni;
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton botonRegistrarCliente;
    private javax.swing.JButton botonReserva;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoCp;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLocalidad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNrPers;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox<String> comboCatering;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDatosCliente;
    private javax.swing.JPanel panelReserva;
    // End of variables declaration//GEN-END:variables

    public void botonRegistrarCliente(){
        if (utilidades.Utilidades.campoVacio(campoNombre)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo nombre esta vacio");
        } else if (utilidades.Utilidades.campoVacio(campoApellidos)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo apellidos esta vacio");
        } else if (utilidades.Utilidades.campoVacio(campoTelefono)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo telefono esta vacio");
        } else if (!utilidades.Utilidades.enteroCorrecto(campoTelefono)) {
            utilidades.Utilidades.lanzarAlertaEntero(this, "El campo telefono es numerico");
        } else if (!utilidades.Utilidades.formatoTelefono(campoTelefono.getText())) {
            utilidades.Utilidades.lanzarTelefono(this, "El telefono no es valido");
        } else if (utilidades.Utilidades.campoVacio(campoEmail)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo email esta vacio");
        } else if (!utilidades.Utilidades.correoCorrecto(campoEmail)) {
            utilidades.Utilidades.lanzaAlertaCorreo(this, "El email no es valido");
        } else if (utilidades.Utilidades.campoVacio(campoDireccion)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo direccion esta vacio");
        } else if (utilidades.Utilidades.campoVacio(campoCp)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo cp esta vacio");
        } else if (!utilidades.Utilidades.enteroCorrecto(campoCp)) {
            utilidades.Utilidades.lanzarAlertaEntero(this, "El campo cp es numerico");
        } else if (!utilidades.Utilidades.formatoCP(campoCp.getText())) {
            utilidades.Utilidades.lanzaAlertaCp(this, "El cp no es valido");
        } else if (utilidades.Utilidades.campoVacio(campoLocalidad)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo localidad esta vacio");
        } else {
            Cliente c = new Cliente(
                campoDni.getText(),
                campoNombre.getText(),
                campoApellidos.getText(),
                Integer.parseInt(campoTelefono.getText()),
                campoEmail.getText(),
                campoDireccion.getText(),
                Integer.parseInt(campoCp.getText()),
                campoLocalidad.getText()
            );
            Conexion.conectar();
            if (ConsultasClientes.registrarCliente(c)) {
                JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");

                campoDni.setEnabled(false);
                campoNombre.setEnabled(false);
                campoApellidos.setEnabled(false);
                campoTelefono.setEnabled(false);
                campoEmail.setEnabled(false);
                campoDireccion.setEnabled(false);
                campoCp.setEnabled(false);
                campoLocalidad.setEnabled(false);
                botonReserva.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this, "Error en el registro. Comprueba el formulario");
                campoDni.setEnabled(true);
                campoNombre.setEnabled(true);
                campoApellidos.setEnabled(true);
                campoTelefono.setEnabled(true);
                campoEmail.setEnabled(true);
                campoDireccion.setEnabled(true);
                campoCp.setEnabled(true);
                campoLocalidad.setEnabled(true);
                botonReserva.setEnabled(false);
            }
            Conexion.cerrarConexion();
        }
    }
    public void botonComDni(){
        Conexion.conectar();
        if (utilidades.Utilidades.campoVacio(campoDni)) {
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo dni esta vacio");
        } else if (!utilidades.Utilidades.formatoDNI(campoDni.getText())) {
            utilidades.Utilidades.lanzarformatodni(this, "El formato del dni no es correcto");
        } else if (!utilidades.Utilidades.dniValido(campoDni.getText())) {
            utilidades.Utilidades.lanzarformatodniValido(this, "El dni no es valido");
        } else if (ConsultasClientes.comprobarDni(campoDni.getText())) {
            Cliente c = ConsultasClientes.rescataDatosCliente(campoDni.getText());

            campoNombre.setText(c.getNombre());
            campoApellidos.setText(c.getApellidos());
            campoTelefono.setText(String.valueOf(c.getTelefono()));
            campoEmail.setText(c.getEmail());
            campoDireccion.setText(c.getDireccion());
            campoCp.setText(String.valueOf(c.getCp()));
            campoLocalidad.setText(c.getLocalidad());
            campoNombre.setEnabled(false);
            campoApellidos.setEnabled(false);
            campoTelefono.setEnabled(false);
            campoEmail.setEnabled(false);
            campoDireccion.setEnabled(false);
            campoCp.setEnabled(false);
            campoLocalidad.setEnabled(false);
            botonRegistrarCliente.setEnabled(false);
            botonReserva.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "No existen clientes registrados con ese DNI");
            campoNombre.setEnabled(true);
            campoApellidos.setEnabled(true);
            campoTelefono.setEnabled(true);
            campoEmail.setEnabled(true);
            campoDireccion.setEnabled(true);
            campoCp.setEnabled(true);
            campoLocalidad.setEnabled(true);
            botonRegistrarCliente.setEnabled(true);
        }
        Conexion.cerrarConexion();
    }
    public void botonReserva(){
        Date d = new Date();
        String catering = (String) comboCatering.getSelectedItem();
        if(fecha.getDate().before(d)){
            utilidades.Utilidades.lanzaAlerta(this, "La fecha tiene que ser posterior a la actual");
        }else if(utilidades.Utilidades.campoVacio(campoNrPers)){
            utilidades.Utilidades.lanzaAlertaCampoVacio(this, "El campo numero de personas esta vacio");
        }else if(!utilidades.Utilidades.enteroCorrecto(campoNrPers)){
            utilidades.Utilidades.lanzarAlertaEntero(this, "El campo numero de personas es numerico");
        }else if(utilidades.Utilidades.combosSinSeleccionar(catering)){
            utilidades.Utilidades.lanzaAlertaComboVacio(this, comboCatering);
        }else{
            Conexion.conectar();
            Salones s = new Salones(
                    campoDni.getText(),
                    fecha.getDate(),
                    Integer.parseInt(campoNrPers.getText()),
                    comboCatering.getSelectedItem().toString(),
                    ConsultasEmpleados.guardarDNI(Login.miusuario)
            );
            areaTexto.setText("");
            if(ConsultasSalones.registrarSalon(s)){
                JOptionPane.showMessageDialog(this, "Reserva registrada correctamente");
                botonFactura.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione el tipo de catering.");
            }
            Conexion.cerrarConexion();
        }
    }
    public void botonFactura(){
        String htexto = s.toString();
        areaTexto.setText(htexto);
    }
    
}
